FIRESTORE_APP = "app"
FIRESTORE_APP_CONFIG = "config"
FIRESTORE_APP_CONFIG_KEY_CLIENT_SECRETS = "client_secrets"

FIRESTORE_USERS = "users"
FIRESTORE_USERS_DEFAULT = "default"
FIRESTORE_USERS_KEY_TOKEN = "token"
FIRESTORE_USERS_KEY_LAST_PROCESSED = "last_processed"

LOCAL_SERVICE_SECRETS = "ytmdl-bbd302757681.json"

YOUTUBE_LIST_LIMIT = 100
