FIRESTORE_APP = "app"
FIRESTORE_APP_CONFIG = "config"
FIRESTORE_APP_CONFIG_KEY_CLIENT_SECRETS = "client_secrets"

FIRESTORE_USERS = "users"
FIRESTORE_USERS_DEFAULT = "default"
FIRESTORE_USERS_KEY_YOUTUBE_TOKEN = "token"
FIRESTORE_USERS_KEY_DRIVE_TOKEN = "drive_token"
FIRESTORE_USERS_KEY_LAST_PROCESSED = "last_processed"
FIRESTORE_USERS_KEY_LAST_TRIGGERED = "last_triggered"
FIRESTORE_USERS_KEY_VIDEOS = "videos"  # subcollection

LOCAL_SERVICE_SECRETS = "CONFIGURE_ME"
TMP_PATH = "/tmp/ytmdl"


YOUTUBE_LIST_LIMIT = 100
