name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=1000 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        # pytest test/unit
    - name: Create gcp_key.json
      env:
        GCP_KEY: ${{ secrets.GCP_KEY }}
      run: |
        echo ${GCP_KEY} > gcp_key.json
    - name: Create sample_secret.json
      env:
        SAMPLE_SECRET: ${{ secrets.SAMPLE_SECRET }}
      run: |
        echo ${SAMPLE_SECRET} > sample_secret.json
    - name: print sample_secret.json
      run: |
        cat sample_secret.json
    - name: Deploy
      run: |
        echo "TBD"
