name: Deploy

on:
  push:
    branches:
    - master

jobs:
  iterate_users:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: exelban/gcloud@master
      env:
        PROJECT_ID: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
        APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
      with:
        args: functions deploy iterate_users --region=us-central1 --entry-point=iterate_users
  process_user:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: exelban/gcloud@master
      env:
        PROJECT_ID: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
        APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
      with:
        args: functions deploy process_user --region=us-central1 --entry-point=process_user
  process_video:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: exelban/gcloud@master
      env:
        PROJECT_ID: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
        APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
      with:
        args: functions deploy process_video --region=us-central1 --entry-point=process_video
